name: 'Jest Coverage Commenter + edit'
description: 'Comment on PRs with Jest Coverage Information'
author: 'Derek Kershner'
inputs:
  github_token:
    description: 'A GitHub Token, the standard one is great'
    required: true
  test_command:
    description: 'The test command to run, that also runs coverage appropriately'
    default: 'npx jest --coverage'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: percent
  color: orange
